language: python
python:
  - "3.2"
env:
  - QT_API=pyqt4
  - QT_API=pyqt5
  - PEP8=1
  - COV=1
matrix:
    allow_failures:
        - env: COV=1
        - env: PEP8=1
        - env: QT_API=pyqt5
virtualenv:
  system_site_packages: true
before_install:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
install:
  # PyQ4
  - sudo apt-get install -qq python3-pyqt4 --fix-missing
  # PyQt5 (won't be available untill travis upgrade to ubuntu 14.04
  - if [ $QT_API = "pyqt5" ]; then
    sudo apt-get install -qq python3-pyqt5 --fix-missing;
    fi
  - pip install git+https://github.com/pyQode/pyqode.core.git@develop
script:
  - pip install .
  - if [ $QT_API ]; then
    python3 runtests.py;
    fi
  - if [ $PEP8 ]; then
    pip install pytest-pep8;
    python3 runtests.py --pep8 -m pep8;
    fi
  - if [ $COV ]; then
    pip install pytest-cov;
    python3 runtests.py --cov pyqode;
    fi
after_script:
  - if [ $COV ]; then
    sudo pip install --quiet coveralls;
    coveralls;
    fi
